### ISSUE TITLE
Tests don't pass on clean repository

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/gorouter#80] opened 2015-04-20 08:48 UTC
I tried to follow the documentation in README.md to get the tests to work:
1. `go get`ing the repo
2. `godep restore`ing the dependencies
3. executing `scripts/test`

*Expected*: The tests run successfully
*Actual*: The tests fail

Here is the test output
```
[1429518944] Gorouter Suite - 5/6 specs [e][gnatsd] [26351] 2015/04/20 10:35:47.018219 [INF] Starting gnatsd version 0.6.0
[e][gnatsd] [26351] 2015/04/20 10:35:47.018329 [INF] Listening for client connections on 0.0.0.0:51253
[e][gnatsd] [26351] 2015/04/20 10:35:47.018477 [INF] gnatsd is ready
{"timestamp":1429518947.169410229,"process_id":26353,"source":"router","log_level":"info","message":"Waiting 1s before listening...","data":null}
{"timestamp":1429518948.171354294,"process_id":26353,"source":"router","log_level":"info","message":"Listening on [::]:51259","data":null}
{"timestamp":1429518948.171914577,"process_id":26353,"source":"router.main","log_level":"info","message":"gorouter.started","data":null}
{"timestamp":1429518953.750549316,"process_id":26353,"source":"router.main","log_level":"info","message":"gorouter.stopping","data":null}
{"timestamp":1429518953.750906706,"process_id":26353,"source":"router.main","log_level":"info","message":"gorouter.stopped","data":{"took":"350.72µs"}}
```
And here is the error at the end:
```
------------------------------
• Failure [6.757 seconds]
Router Integration Drain [It] prevents new connections
/Users/voelzmo/go/src/github.com/cloudfoundry/gorouter/main_test.go:247

  Expected
      <bool>: false
  to be true

  /Users/voelzmo/go/src/github.com/cloudfoundry/gorouter/main_test.go:225
------------------------------
```

Then, the entire test script hangs and I have to `ctrl+c` to exit.

I'm working on Yosemite and here is the output of `go env` if that is helpful:
```
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/voelzmo/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.4.2/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.4.2/libexec/pkg/tool/darwin_amd64"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fno-common"
CXX="clang++"
CGO_ENABLED="1"
```

**Comment by DanLavine** [comment] 2015-04-20 18:22
Hi @voelzmo,

Thanks for bringing this to our attention. It looks like we have some flaky tests and we created a [story](https://www.pivotaltracker.com/story/show/92852938) to fix these problems. We have not noticed the the script hanging and needing to manually kill it. That sounds like it could be some sort of race condition hanging, but we run our tests with Go's race detection. If you can replicate the hang it would be useful to have the random seed that the tests run with so we could try it. 

Thanks,
@utako && @DanLavine, The CF Runtime Team

**Comment by voelzmo** [comment] 2015-04-21 07:30
@DanLavine thanks for creating the story. However, all I can see using this link is `You are not allowed to view the requested page.` - Is there a way to move this somewhere public so I can track this?

The test script seems to hang all the time for me, so I'm not sure if there is a different issue with my test setup here. The seed in the last run I did was `1429601203`. Thanks for looking into this!

**Comment by dieucao** [comment] 2015-04-21 09:14
@voelzmo I ended up deleting the story he linked as it was a duplicate of this [one] (https://www.pivotaltracker.com/story/show/91653940)

**Comment by voelzmo** [comment] 2015-04-21 11:14
Thanks @dieucao, that link works!

**Comment by zaksoup** [comment] 2015-04-23 18:10
@DanLavine finished that story. Tests should be less flaky now. Thanks again for bringing this up!

**Closed by zaksoup** 2015-04-23 18:10 UTC

**Comment by voelzmo** [comment] 2015-04-24 10:59
@DanLavine @zaksoup Thanks for fixing this so quickly!
