### ISSUE TITLE
Header values missing after passing through the Go Router

### ISSUE THREAD

**Issue by HiteshNembhwani** [cloudfoundry/gorouter#217] opened 2018-06-08 22:53 UTC
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

Header values are missing after passing through the Go Router (details and the logs in the attached PDF)

*Impacting our customer to Go-Live and we haven't been able to figure a workaround for this one.*  

Tried the open source and Pivotal Slack channel and have been suggested to open an issue on GH. 

## Context

TIBCO BusinessWorks Container Edition (BWCE) apps are deployed on PIE-21 environment
provided by PCF via Partner Slack channel.
This BWCE app is a simple SOAP based service.
These BWCE apps are missing context header values when deployed in a PCF environment.

## Steps to Reproduce

Deployed a sample BWCE app on PIE 21 environment shared by PCF and verified that
headers are not received in SOAP Response. 

Hitting this URL -
https://nitish-service-subscriber.cfapps.pie-srt-21.cfplatformeng.com/soap/v1

Used SOAP UI to make SOAP requests.

Router Log message -
2018-06-08T11:00:14.621-07:00 [RTR/0] [OUT]
nitish-service-subscriber.cfapps.pie-srt-21.cfplatformeng.com -
[2018-06-08T18:00:14.619+0000] "GET / HTTP/1.1" 404 0 1267 "-" "Mozilla/5.0
(Windows; U; Windows NT 6.1; en-US) AppleWebKit/534.16 (KHTML, like Gecko)
Chrome/10.0.648.133 Safari/534.16" "130.211.0.240:61601" "192.168.16.12:61028"
x_forwarded_for:"208.87.233.140, 35.201.66.36, 130.211.0.240"
x_forwarded_proto:"https"
vcap_request_id:"f15b7f0b-c02f-45a0-5dcc-b6f4e56b6ce3"
response_time:0.002043168 app_id:"e0782e24-3286-4484-9bd4-654788d1e059"
app_index:"0" x_b3_traceid:"674d57cd260fcaff" x_b3_spanid:"674d57cd260fcaff"
x_b3_parentspanid:"-"

● Accessed the router and application VMs on PCF to make SOAP curl requests. 
The sample BWCE app was able to retrieve the headers in SOAP response when we hit
the application VM directly , however, the application was unable to retrieve the
headers when the request was made via the router VM .

CURL Router VM Request:

curl -H “Host: nitish-soap-sample-with-ver.apps.xxxx.xxxx.com ” -H ‘usn:val’ -H
‘version:val’ -H ‘content-type:appplication/json’ -H “SOAPAction:urn:getProfile” --data
@request.xml localhost:80/soap/v1 -vvv
Router Log while sending the CURL request -
[2018-06-04T23:00:02.908+0000] "POST /soap/v1 HTTP/1.1" 200 2410 604 "-"
"curl/7.35.0" "127.0.0.1:57816" "10.0.4.29:61050" x_forwarded_for:"127.0.0.1"
x_forwarded_proto:"http" vcap_request_id:"23c0eb67-bca9-4ee0-7e35-f8405107ab53"
response_time:0.016911198 app_id:"382f2e97-4f83-4acf-ac63-6fa013bf4b5e"
app_index:"0" usn:"val" version:"val" x_b3_traceid:"30f715e91a8cfe70"
x_b3_spanid:"30f715e91a8cfe70" x_b3_parentspanid:"-"

CURL Application VM Request:
curl -v -H ‘usn:val’ -H ‘version:val' -H ‘content-type:appplication/json’ -H
“SOAPAction:urn:getProfile” --data @request.xml 10.0.4.29:61050/soap/v1

## Expected result

Header value for *usn* should be populated. 

## Current result

Header value for *usn* is blank after it passed through the Go Router. 

## Possible Fix

not applicable

## `name of issue` Output Results

[if relevant, include a screenshot]
[PCF-Issue-BWCE_SOAPHeaders.pdf](https://github.com/cloudfoundry/gorouter/files/2086392/PCF-Issue-BWCE_SOAPHeaders.pdf)

**Comment by HiteshNembhwani** [comment] 2018-06-08 22:54
@shalako please please help prioritizing this issue, thanks!

**Comment by shalako** [comment] 2018-06-09 00:11
OSS Slack thread: https://cloudfoundry.slack.com/archives/C05586PBX/p1527624306000545

**Comment by shalako** [comment] 2018-06-09 00:17
We have been unable to reproduce the issue with our own test apps. 

Please provide the app you are testing with, and instructions for deploying it, so that we can attempt to reproduce the issue.

**Comment by adobley** [comment] 2018-10-04 17:09
@HiteshNembhwani I am closing this for now, please feel free to reopen if you are still experiencing this issue. Thanks!

**Closed by adobley** 2018-10-04 17:09 UTC
Labels: unscheduled
