### ISSUE TITLE
gorouter access logs report HTTP 502 in case the client goes away

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/gorouter#192] opened 2017-09-19 16:00 UTC
Thanks for submitting an issue to `gorouter`. We are always trying to improve! To help us, please fill out the following template.

## Issue

When the client goes away before the response is completely sent to the client the gorouter access logs incorrectly report status 502.

## Context

cf-release 254

## Steps to Reproduce

- deploy an app that slowly sends a 200 response back to the client
- send a request to the app, close the connection before the client receives the full response body (e.g. using `curl -m`)
- notice that the client (if the connection gets closed after the response headers are received but before the body is completely received) gets a HTTP 200
- notice that in the gorouter access logs the status is recorded as 502

## Expected result

I am not sure what are the semantics of the status code in the gorouter access logs:

- if it's supposed to be the status code returned to the client, it should be the status code that was sent to the client optionally decorated to signify that the client didn't receive the full response, or a special status code (like nginx 499) that signifies that the client didn't receive the full response
- if it's supposed to be the status code returned by the application, it should be the status code returned by the application regardless of what happened to the client

## Current result

The gorouter access logs show 502, as if the application was unable to process the request.
This is highly misleading because the client going away can't be classified as a "server error" (HTTP 5xx) 

It seems the current tests only check that an error is returned in this case, but not which error: https://github.com/cloudfoundry/gorouter/blob/fb82e88b59b76b136429da15e1c324d01d5f09a4/proxy/proxy_test.go#L1004

**Comment by shalako** [comment] 2017-09-19 20:08
In general, the status code logged in access logs is the one returned to the client. Since the client closed the connection it seems appropriate to log a 499.

**Comment by charleshansen** [comment] 2017-10-11 21:41
In the most recent routing-release, we were unable to recreate the 502 behavior. The access logs will log the status code returned to the client (200 in this case).  Is it still worth it to change the behavior to make it a 499?

**Comment by giner** [comment] 2017-10-11 23:09
Probably it isn't. Let me try to find when the behavior of gorouter changed.

**Comment by giner** [comment] 2017-10-12 10:23
It is reproducible with routing-release 0.163.0
```
$ curl -m 1 test.bosh-lite.com
curl: (28) Operation timed out after 1000 milliseconds with 0 bytes received

$ curl -m 6 test.bosh-lite.com
Hello RPaaS v2!
```

```
$ cf logs test
Retrieving logs for app test in org system / space test as admin...

   2017-10-12T19:21:57.75+0900 [RTR/0] OUT test.bosh-lite.com - [2017-10-12T10:21:56.878+0000] "GET / HTTP/1.1" 502 0 67 "-" "curl/7.35.0" "192.168.50.1:45316" "10.244.0.139:61002" x_forwarded_for:"192.168.50.1" x_forwarded_proto:"http" vcap_request_id:"629f0753-9b73-4fe5-7f88-44dd48d3a6af" response_time:0.876052124 app_id:"4822c590-eaa3-4ac2-bb99-dcf4635c1c5f" app_index:"0" x_b3_traceid:"20970de6d990e66e" x_b3_spanid:"20970de6d990e66e" x_b3_parentspanid:"-"
   2017-10-12T19:21:57.75+0900 [RTR/0] OUT 
   2017-10-12T19:22:17.03+0900 [RTR/0] OUT test.bosh-lite.com - [2017-10-12T10:22:12.030+0000] "GET / HTTP/1.1" 200 0 16 "-" "curl/7.35.0" "192.168.50.1:45348" "10.244.0.139:61002" x_forwarded_for:"192.168.50.1" x_forwarded_proto:"http" vcap_request_id:"7cf44979-9b14-4afc-6bfc-049a21f8a2c8" response_time:5.003135032 app_id:"4822c590-eaa3-4ac2-bb99-dcf4635c1c5f" app_index:"0" x_b3_traceid:"3cde177aff8d71d1" x_b3_spanid:"3cde177aff8d71d1" x_b3_parentspanid:"-"
   2017-10-12T19:22:17.03+0900 [RTR/0] OUT 
```

Here is the code I used for testing:
```
$ cat main.go
package main

import (
	"io"
	"log"
	"net/http"
	"os"
	"time"
)

const (
	EnvPort = "PORT"
)

func main() {
	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                time.Sleep(5* time.Second)
		io.WriteString(w, "Hello RPaaS v2!\n")
	})

	port := os.Getenv(EnvPort)
	log.Println("[INFO] Listening on", port)

	log.Fatal(http.ListenAndServe(":"+port, nil))
}
```

**Comment by flawedmatrix** [comment] 2017-10-13 21:49
The code you used for testing seems to describe a different scenario from what was described in the original issue.

What we used for testing was something along the lines of
```
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	time.Sleep(5* time.Second)
	io.WriteString(w, "Hello RPaaS v2!\n")
})
```
which would return a 200 to the client first, and then slowly return the body, whereas

```
http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
	time.Sleep(5* time.Second)
	io.WriteString(w, "Hello RPaaS v2!\n")
})
```
would wait 5 seconds before sending a 200 to the client and then a subsequent body.

If the client connection is closed before Gorouter receives the response headers from the client, then the result is a 502 in the access logs.

**Comment by charleshansen** [comment] 2017-10-13 22:34
We looked into this a little bit, I'm pretty sure we can easily detect this case and log a 499 instead of 502. One minor caveat is that you cannot cancel requests through the gcp or aws load balancers. Cloud Foundries with those load balancers will always log status code 200 in that case because the request is not actually cancelled.

**Comment by giner** [comment] 2017-10-15 04:34
@flawedmatrix, you are right. I tried to reproduce the original issue with routing-release 0.147.0 and was unable to do it. I suppose our original understanding was not entirely correct and the problem happens only when client goes away without receiving a header.

**Comment by shubhaat** [comment] 2017-10-30 19:39
@giner We have validated that the change is working as expected on Release Candidate. It will be included in the next final release of routing-release (0.166.0).

```
curl 127.0.0.1/delay/10 -H "Host: dora-shubha.superman.cf-app.com" -m 5
curl: (28) Operation timed out after 5001 milliseconds with 0 bytes received
```

```
$ cf logs dora
...
   2017-10-30T12:36:43.49-0700 [RTR/0] OUT dora-shubha.superman.cf-app.com - [2017-10-30T19:36:38.492+0000] "GET /delay/10 HTTP/1.1" 499 0 22 "-" "curl/7.35.0" "127.0.0.1:6334" "10.0.16.16:61004" x_forwarded_for:"127.0.0.1" x_forwarded_proto:"http" vcap_request_id:"9f9b5740-430e-4731-7dea-468320eafaec" response_time:5.002285898 app_id:"bae99372-5813-43b7-b890-07b09df7dfd1" app_index:"0" x_b3_traceid:"fd4b0d48b0406935" x_b3_spanid:"fd4b0d48b0406935" x_b3_parentspanid:"-"
```

**Closed** 2017-10-30 19:40 UTC
Labels: accepted
