### ISSUE TITLE
Issues with zipkin headers

### ISSUE THREAD

**Issue by dsyer** [cloudfoundry/gorouter#157] opened 2016-12-12 14:48 UTC
It appears that the router is adding a new span to the current trace if there is one. You can test it by sending in a traceid and spanid and seeing the logs from the router

```
$ curl sleuthy.cfapps.io/hi -H "X-B3-TraceId: 6e97e1ffea683c88" -H "X-B3-SpanId: 6e97e1ffea683c88"
```

```
2016-12-12T14:31:45.41+0000 [RTR/0]      OUT sleuthy.cfapps.io - [12/12/2016:14:31:45.395 +0000] "GET /hi HTTP/1.1" 200 0 2 "-" "curl/7.47.0" "10.10.2.227:52070" "10.10.155.26:62369" x_forwarded_for:"82.7.92.18" x_forwarded_proto:"http" vcap_request_id:"57d9eda2-ce8a-40e3-52f8-a3e54e502832" response_time:0.014604874 app_id:"a498dc22-f9e5-4ad3-83dc-f5971c1a2426" app_index:"0" x_b3_traceid:"6e97e1ffea683c88" x_b3_spanid:"e937b5630338a6ff" x_b3_parentspanid:"6e97e1ffea683c88"
```

And the Spring Sleuth `TraceFilter` reports `e937b5630338a6ff` as the current span (of course). But that one has appeared out of thin air. The only place it could have come from is the router. I guess maybe that does make sense (the router is an extra hop in the trace). But with Zipkin in the picture it all goes to pot because there are no logs or annotations on the fabricated span. If the router is not going to be in the business of sending span data to zipkin, maybe it ought to refrain from creating new spans? Ideally, the creator of a new span should always perform a sampling computation, to decide whether or not the span is eligible for export to Zipkin. If the router is not going to be doing that computation, that's another reason not to be creating spans.

Also the router is adding "X-B3-ParentSpanId: -" (i.e. invalid identifier) in the case that the spanid is not present in the incoming request. That could be screwing things up as well. You end up with an unrooted span in Zipkin that ought to be a child of the span with the same id as the trace.

**Comment by shalako** [comment] 2016-12-12 18:44
Hi Dave,

Having the router assign spans to parent spans was the behavior we agreed on with @adriancole. We have no plans currently to have the router send data to a Zipkin deployment, as the MVP for this effort was to enable correlation of router and app logs in CF.

> Also the router is adding "X-B3-ParentSpanId: -" (i.e. invalid identifier) in the case that the spanid is not present in the incoming request.

This was a behavior that we discovered that broker Sleuth-enabled apps and has since been fixed. Testing on PWS, you shouldn't see this behavior.

If the router doesn't create spans, is there still value in having any support for Zipkin headers in the router at all? Does it still help an app developer to look at logs and see just that the router logged the traceid only?

**Comment by shalako** [comment] 2016-12-12 18:48
Confirmed on PWS that when trace and span are not present in the request, the router does not send the `X-B3-ParentSpanId` header. It does log the null value `x_b3_parentspanid:"-"`, as is our convention.

**Comment by shashwathi** [comment] 2017-01-21 05:44
@dsyer : 

Thank you for raising with issue. Looks like @shalako confirmed that this is fixed in recent cf-release. Closing this issue for now. Feel free to reopen this or another issue if you have any problem.

Regards
Shash

**Closed by shashwathi** 2017-01-21 05:44 UTC
Labels: unscheduled

**Comment by XuejiaoZhang** [comment] 2018-01-05 05:09
Hi @dsyer & @shalako 
Sorry to disturb you. I'd like to ask a question related to the Zipkin Tracing logs.

After I enabled Zipkin feature by setting "enable_zipkin: true", I run 
`curl xxxxx/hi -H "X-B3-TraceId: 6e97e1ffea683c88" -H "X-B3-SpanId: 6e97e1ffea683c88"`
The gorouter log shows "... x_b3_traceid:"6e97e1ffea683c88" x_b3_spanid:"6e97e1ffea683c88" x_b3_parentspanid:"-" ...". 

I'm wondering why the Gorouter didn't create a new span, set the previous span as the parent span.
Would you please give me a quick clue about what's missing there? 
Thank you very much in advance.
