### ISSUE TITLE
Route does not fail hard when app is down 

### ISSUE THREAD

**Issue by prettyClouds** [cloudfoundry/gorouter#207] opened 2018-02-02 04:00 UTC
If an app is entirely down and a route is mapped to it, the router ignores the app entirely and searches for the next best match.

Reproduction steps:

Deploy app1 and app2.
map abc.com to app1
map abc.com/def to app2
stop app2
curl abc.com/api/def
a request is made to app1

Expectation
I would expect an HTTP status of 500 from the request

Is this fallback strategy intentional? In my particular case app1 is a push-state enabled staticfile app, so the request returns a 200 and a bunch of html.  I want the request to fail hard if app2 is down.

**Comment by shubhaat** [comment] 2018-02-02 18:21
This is expected behavior.

Whether app2 is up or down, we would expect a request for `abc.com/api/def` to be routed to app1 because the route `abc.com` will match any context path; think of this route as `abc.com/*`. The route `abc.com/def`, will only match requests to `abc.com/def` and `abc.com/def/*`. So a request to `abc.com/api/def` will match the route `abc.com/*`, not `abc.com/def`. 

See https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html for details.

If you would like requests for `abc.com/api/def` to be routed to app2, create a route `abc.com/api` or `abc.com/api/def`.

By the way, when an app is stopped and the route mapped to it is not mapped to another app, the route will be removed from the routers routing table along with knowledge of the backends for the stopped app. In your case, when app2 is stopped the router has no knowledge of the route `abc.com/def`. If you have no other routes for this domain than `abc.com` then all requests for any context path of `abc.com` will be routed to app1. 

We are currently working on the next generation of our routing subsystem and this behavior will change. We intend to requests for `abc.com/def/*` receive a 503 when the mapped app is stopped.

**Comment by prettyClouds** [comment] 2018-02-04 16:58
sorry i had typo in the description of the problem.  i meant to say map `abc.com/api/def` to app2. I expected some 50x status but instead when app2 was down, but received a 200 from app1 because it was a front-end app with push-state enabled. looks like that behavior will be changing 👍 i am happy to close this if there is already a story or issue tracking this.  I do think the case where the 'fallback' app is a staticfile, push-state enabled instance might be interesting to track and test against

**Comment by shubhaat** [comment] 2018-03-14 01:03
Closing this issue since we don't plan to support it in Gorouter but definitely want to support it in the new Istio based routing subsystem. The proposal is here: https://docs.google.com/document/d/1LgLY0g39fzpg1_4zTckbH1mOuuSKGvYwp2tkakoe9ys/edit

**Closed by shubhaat** 2018-03-14 01:03 UTC
Labels: unscheduled
