### ISSUE TITLE
Gorouter likely to lose routes when NATS VM crashes hard

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry/gorouter#132] opened 2016-05-10 04:22 UTC
We found out by hard crashing NATS VMs that gorouter (as well as other components, like CC) fail to quickly failover to the other NATSes in the cluster. This does not happen if the NATS process crashes (in this case the OS on the NATS VM will close the sockets), it happens only when the whole VM crashes.

While other components are also affected, gorouter is the worst affected because this problem leads to lost traffic.

All of our gorouter settings for timeouts are the default ones. We're using cf-release 220, both NATS and gorouter are on openstack, the stemcell in use is 3215.

In practice we see that roughly 100-110s after the crash of the NATS VM the routers that were connected to that specific NATS VM forget the routes. After a few minutes the disconnection is finally detected and a new connection established.

We're still investigating and confirming, but the most likely culprit is in the pingInterval setting: https://github.com/cloudfoundry/gorouter/blob/64cf29ce174e04a955b883e0d270e158d67bd176/config/config.go#L190-L203. While it's true that the NATS client will detect the disconnection after two failed ping attempts, it's not correct to say that the disconnection will happen within `2*PingInterval` (as the comment above that code says): it will actually happen _after_ 2 failed attempts, and this means that it will take between `2*PingInterval` and `3*PingInterval` to disconnect. (see https://github.com/nats-io/nats/blob/6f8a5734602782ce3ab3874b474a1b215acc7ed8/nats.go#L2186-L2193)

To be on the safe side, we should also consider that reconnection is not immediate (it should be fast, but it's not immediate) so my guess is that the full, worst-case reconnection time is `3*PingInterval + (NumNATSServers-1)*NATSConnectionTimeout` and all of this should be lower than `dropletstalethresholdinseconds/2 - startresponsedelayintervalinseconds`. This is the bare minimum, we may even want to add a small extra time buffer to avoid playing with fire.

Until this is fixed, a crash of one of the NATS VMs will most likely result in lost traffic.

**Comment by markstgodard** [comment] 2016-05-10 14:49
Hi @CAFxX 

We recently worked on a story related to gorouter and failing over to another NATS instance  and pruning routes:  https://www.pivotaltracker.com/story/show/110199022

This is not yet in an official CF release, but should be in the next.

Essentially gorouter was pruning routes BEFORE reconnecting to a new NATS instances. We also had to review and reconcile all the "intervals" and "thresholds" that we had going on that related to gorouter, deas, diego and NATS.  

We will review and see if we have your case covered.

Cheers

**Comment by sharms** [comment] 2016-07-29 17:53
Ran into this last night, any update on a fix being committed?

**Comment by flawedmatrix** [comment] 2016-08-25 19:21
@sharms @CAFxX 

We are closing this issue because we pulled in a fix: https://github.com/cloudfoundry/gorouter/pull/140

This is already part of version 0.137.0 of [routing-release](https://github.com/cloudfoundry-incubator/routing-release/tree/0.137.0) and will be part of the next final release of CF Release.

**Comment by CAFxX** [comment] 2016-08-26 03:52
@flawedmatrix are you sure #140 will fix the issue? Because it looks like that will only kick in if the natsClient *thinks* we're not connected. The problem described in this ticket is that the natsClient thinks we're still connected, even though the NATS server died.

**Comment by CAFxX** [comment] 2016-10-24 00:09
@flawedmatrix *ping*

**Comment by sharms** [comment] 2016-11-01 17:46
Still an issue, can we re-open this?

**Comment by crhino** [comment] 2016-11-02 19:01
@CAFxX The nats client will set its status based on attempting to [ping the nats server](https://github.com/nats-io/nats/blob/aab6caaf3a868d3f1a8cd87b7c34b364306df278/nats.go#L1301-L1334), we have currently [hard-coded the PingInterval](https://github.com/cloudfoundry/gorouter/blob/308c2545a695d544d712bf6c769b10f577b49fb6/config/config.go#L201) to be 20 seconds. Since the [stale threshold value is 120 seconds](https://github.com/cloudfoundry-incubator/routing-release/blob/311f70a8c2824dfe13a53f7d962832a0c1af23b8/jobs/gorouter/templates/gorouter.yml.erb#L42), the 20 second ping interval allows for ample amount of time to attempt to reconnect before pruning routes. To my understanding, this change to the ping interval fixes the issue here.

#140 improves on this by allowing operators to suspend pruning indefinitely if NATs has a catastrophic failure and no NATs servers are available to reconnect to.

@sharms Have you seen this issue recently? If so, what version of CF are you using?

**Comment by shalako** [comment] 2016-11-02 19:22
The change to the ping interval was introduced in routing-release v138 and in cf-release v243

**Comment by shashwathi** [comment] 2017-01-20 21:26
@CAFxX : 
Are you still experiencing this issue? If not, please feel free to close this thread.
Regards
Shash

**Comment by CAFxX** [comment] 2017-01-20 22:32
We will reach v243 in a few weeks: we can keep this issue open until we can confirm - or we can close it now and reopen later if the fix didn't solve.

**Comment by giner** [comment] 2017-02-22 09:26
Deployed and tested v243.

With default settings it is still possible that routes get lost. This happens in case requested_route_registration_interval_in_seconds >= 10 (default is 20). If it is set to 5 no routes get lost when NATS crashes.

I.e. gorouter should keep routes for at least "nats failover timeout" + "route registration interval":
**prune_stale_droplets_interval** (30s is default) > **nats failover timeout** (20s) + **requested_route_registration_interval_in_seconds** (20s is default).`

**Comment by shashwathi** [comment] 2017-02-22 20:58
@giner 
> gorouter should keep routes for at least "nats failover timeout" + "route registration interval":
prune_stale_droplets_interval (30s is default) > nats failover timeout (20s) + requested_route_registration_interval_in_seconds (20s is default).`

There is some misunderstanding about the property `prune_stale_droplets_interval` and `droplet_stale_threshold `.  
`prune_stale_droplets_interval` is the interval used by gorouter to periodically check whether there are any stale routes in routing table.
`droplet_stale_threshold`:  After this period, gorouter marks route as stale. 

 By the above logic 
`"nats failover timeout"(20s) + "route registration interval"(20s) < droplet_stale_threshold (120s is default) `
There is additional 60 sec interval provided for nats to come online and heartbeat the routes. With current default settings there should be no downtime during nats failover. 

Can you verify the above values from config file on the router vm ? 

Regards
Shash

**Comment by giner** [comment] 2017-02-22 23:02
Interesting. In my case routes dropped in less than one minute after nats crashed. Let me do more tests.

**Comment by giner** [comment] 2017-02-27 03:58
Hi @shashwathi. Thank you for the detailed explanation.
I didn't manage to reproduce the issue anymore. Gorouter does not get any routes lost.

**Comment by swetharepakula** [comment] 2017-02-28 19:17
Hi @giner, @CAFxX, @sharms,
It sounds like CF v243 fixed/alleviated the problem. We are going to close this issue for now, but please let us know if you experience the problem again and we can reopen this.

Thanks,
@swetharepakula && @aaronshurley 
CF Routing Team

**Closed by swetharepakula** 2017-02-28 19:17 UTC
Labels: accepted, unscheduled
