### ISSUE TITLE
replacing gosteno with lager causing huge performance degradation

### ISSUE THREAD

**Issue by milkotodorov** [cloudfoundry/gorouter#119] opened 2016-03-08 17:03 UTC
Hi @crhino ,

I've found that since commit "replacing gosteno with cf_lager" f97f07c13c79e60a0048975e9639a99e8310ad0a there is a huge performance degradation regarding the requests that can be processed by the gorouter (about 10x times and more in some cases). In this commit there is a replacement of the existing gosteno logging library with the lager one, which seems to cause this performance slowdown.

The following diagrams are all made on AWS - gorouter is running on a c3.2xlarge VM (8x CPU/15GB RAM). I use an application which can handle directly on a single instance about 4000-4500 req/sec and it is scaled to 4 instances. And nGrinder to generate as a loadgenerator. Each request is 1024 bytes and the app replies with 1024 bytes back. 

With gorouter v229 commit 8f63d53079e572cbfc1cfba9c07c58499a280224 sending the requests directly to the gorouter the result looks like this:
![v229_8f63d53](https://cloud.githubusercontent.com/assets/14890886/13608313/8442c5a2-e554-11e5-968c-5fb2abcdb0a8.png)

The same look like if I try to send a fake requests to the router (to an non-existing app), so it can simply reply with 404. 

However with gorouter v229 commit f97f07c13c79e60a0048975e9639a99e8310ad0a the same scenario looks like this:

![v229_f97f07c](https://cloud.githubusercontent.com/assets/14890886/13608746/73afa1f4-e556-11e5-8792-4fc22c22266c.png)

By the way in this last scenario if I fake the requests again I can reach more than 10,000 req/sec. I assume that on a bigger VM could be much more. Unfortunately this is quite resource consuming.

Regards,
Milko

**Comment by milkotodorov** [comment] 2016-03-08 17:51
And something in addition that I've noticed is that one of the CPUs of the gorouter VM is utilized much more than the others (above 90%), while some of the other CPUs are less than 50% utilized.

**Comment by milkotodorov** [comment] 2016-03-09 12:22
Additionally I replaced my app with NGINX httpserver (using the staticfile-buildpack) and there is no difference with the requests the the gorouter can handle. So I think this is its maximums. I saw a research question on the pivotal about this, but cannot write into there, so I post it here.

**Comment by shashwathi** [comment] 2016-03-14 22:07
@milkotodorov 
Thanks for reporting this!

We have found that the commit that caused the performance degrade was [55d71](https://github.com/cloudfoundry/gorouter/commit/55d71d9efde628a00906e70281a65387144b3bf1).  The GoRouter was writing two messages as opposed to one in the previous commit in various places.
```
rt.handler.Logger().Set("Error", err.Error())
rt.handler.Logger().Warnf("proxy.endpoint.failed")
```
was changed to
```
rt.handler.Logger().Error("Error", err)
rt.handler.Logger().Info("proxy.endpoint.failed")
```

We have addressed this issue in commit [a8c61](https://github.com/cloudfoundry/gorouter/commit/a8c6189ff1170572fbce5ceccb836289be581abd) which is part of CF v231.

```
rt.handler.Logger().Error("proxy.endpoint.failed", err)
```

We have tested the fix and the results are comparable with commit [f97f07] (https://github.com/cloudfoundry/gorouter/commit/f97f07c13c79e60a0048975e9639a99e8310ad0a) prior to switching the logging framework.

Please let us know if you still see the same performance issue after deploying CF v231.

Regards
@leochu and @shashwathi
CF Routing Team

**Comment by shalako** [comment] 2016-03-16 01:17
Hello @milkotodorov,

When you have a chance, please run the same tests against Gorouter in v231 of cf-release. We believe we have resolved the issue and are anxious for your confirmation.

Thank you!

**Comment by milkotodorov** [comment] 2016-03-22 09:55
Hi @shashwathi, @shalako, @leochu,

all the submits that you mentioned are quite old - the last one is from 9.Feb. When I posted this issue on 8.Mar I used the latest commit available. I don't think the mentioned submits will improve the performance.

Regards,
Milko

**Comment by shalako** [comment] 2016-03-22 23:09
Hello @milkotodorov 

Could you please provide the latest sha or final release of cf-release that you have tested with? Your post refers to v229.

Thank you

**Comment by milkotodorov** [comment] 2016-03-23 12:27
Hi @shalako,

this can be reproduced with 15e5d4a2173a978f87c0903cdda1eea374afdfbf (and I beleive with the latest too as there's nothing relevant changed). 

As I mentioned since commit 8f63d53079e572cbfc1cfba9c07c58499a280224 (replacing gosteno with lager) this issue occurs.

Regards,
Milko

**Comment by shalako** [comment] 2016-04-01 01:21
Hello @milkotodorov we believe we have fixed the issue with the following commits:

gorouter:

- Upgrades lager to latest (includes fix for json marshalling)
  https://github.com/cloudfoundry/gorouter/commit/ec07b7536cf3c0941db3f1bb7f517351f220f856
- Make access log streaming optional
  https://github.com/cloudfoundry/gorouter/commit/daf6f5a763ec87aef9f9f3e7e2b49677236e6105

cf-release:

- Update fixtures for enable_access_log_streaming (just test fixtures being updated for this SHA)
  https://github.com/cloudfoundry/cf-release/commit/e6943d3d78e5b038cbf628d35a854fa4c8ef02c9
- Spec and template changes
  https://github.com/cloudfoundry/cf-release/commit/6dd214a6a7f8bee2784ad55a4061f3753aa28ea7
  https://github.com/cloudfoundry/cf-release/commit/16b2cb2d833982f422c51b153063cbcf9ca36637

I have verified that after these commits, a load test against a basic app was 3x faster (in requests/sec). These commits result in the access.log no longer being written to stdout or to gorouter_ctl.log, or streamed to syslog. access.log is still written locally.

Streaming of access log to syslog can now optionally be enabled using `router.enable_access_log_streaming`.

These changes will be included in cf-release v234.

Please test by deploying cf-release from release-candidate branch and let us know if this resolves the issue. 

Thank you!

**Comment by milkotodorov** [comment] 2016-04-01 11:32
Hi @shalako,

turning off the access log in a productive environment sounds not like a good solution, especially in a productive environment, don't you think so? As for the fix in the latest lager - I'll give it a try and will give you feedback.

Regards,
Milko

**Comment by markstgodard** [comment] 2016-04-01 11:58
Hi Milko

Access logs will still be written to /var/vcap/sys/log/gorouter/access.log by default. The change was to make sending access logs to also to syslog via stdout optionally and by default set to false. So you should NOT see access log data also being written to /var/vcap/sys/log/gorouter_ctl.log

So access logs will be written as normal, we have not turned them off. Just the optional sending them to syslog. 

Let us know how it goes, thx

Cheers

**Comment by milkotodorov** [comment] 2016-04-05 12:08
Hi,

I've compiled the latest gorouter and tried replacing only the gorouter without updating the whole CF, but I cannot see some improvement. Additionally in the branch release-candidate of cf-release I cannot see v234.

Regards,
Milko

**Comment by markstgodard** [comment] 2016-04-05 12:32
Hi Milko

If you brought in the latest gorouter as well as the gorouter job template changes in cf-release,  are you seeing access logs also being written to /var/vcap/sys/log/gorouter_ctl.log?

I believe v234 should be released this week 

Thanks

**Comment by shalako** [comment] 2016-04-05 16:38
@milkotodorov it is not enough to update the gorouter. Templates have changed in cf-release which support configuration changes in gorouter. Please build cf-release from release-candidate branch and retest.

**Comment by milkotodorov** [comment] 2016-04-06 07:48
hi @shalako, @markstgodard,

I understand. Are there any possibility to apply these configuration changes on CF without building and deploying the new version (on a already deployed one)?

Thanks

**Comment by markstgodard** [comment] 2016-04-06 12:32
Hi @milkotodorov 

Technically yes, however it may get a little more difficult for us to determine what is actually under test.

**cf-release:**
The cf-release job / template changes related to this is:
https://github.com/cloudfoundry/cf-release/commit/16b2cb2d833982f422c51b153063cbcf9ca36637#diff-dae3917af5c65421e4c84ffe12263cad

These changes basically update the structure of gorouter.yml and make the streaming of access log data to stdout configurable (default to false).

**gorouter:**
These two shas are important to have in your version of the gorouter:

Upgrades lager to latest (includes fix for json marshalling)
https://github.com/cloudfoundry/gorouter/commit/ec07b7536cf3c0941db3f1bb7f517351f220f856

Make access log streaming optional
https://github.com/cloudfoundry/gorouter/commit/daf6f5a763ec87aef9f9f3e7e2b49677236e6105


The key is to see if access log data is being sent to /var/vcap/sys/log/gorouter_ctl.log or not.

Cheers

**Comment by shalako** [comment] 2016-04-07 22:29
@milkotodorov Final release v234 has been cut, and includes immediate fixes to the performance regression. Please upgrade your test environment to this release, rerun your performance tests, and let us know the results?

We do not recommend hot-patching VMs as (1) these changes are ephemeral, and (2) it is much harder for us (or anyone else) to reproduce your environment. We use BOSH exclusively for managing change in our environments as the results are repeatable.

**Comment by milkotodorov** [comment] 2016-04-08 08:52
Hi @shalako, thanks for the update. I'll do it with v234. I just wanted to hot-patch the VMs as I had troubles with the upgrade, but will have to do it anyway. I'll keep you posted.

**Comment by shalako** [comment] 2016-04-29 18:50
@milkotodorov We're going to close this issue because we haven't heard from you in three weeks. We assume you have confirmed that the performance degradation has been resolved.

**Closed by shalako** 2016-04-29 18:50 UTC

**Comment by milkotodorov** [comment] 2016-06-09 07:29
Hi @shalako, sorry about this delayed reply. I do confirm that the problem with the performance is fixed with the v234. However I noticed a problem when we scaling the gorouter with  6 or more instance, but this is another issue and I'll open a separate one for it.
